#!/bin/bash

pkill -f dgraph;pkill -f dgraph;pkill -f dgraph;

test_name=$0

logs_dir=$PWD"/logs/${test_name:2}"
data_dir=$PWD"/data/${test_name:2}"

rm -rf $logs_dir; mkdir $logs_dir
rm -rf $data_dir; mkdir $data_dir


if ! [[ -d tls ]];
then
	dgraph cert
	dgraph cert -c live
	dgraph cert -n localhost
fi

o="0"
dgraph zero -w "z$o" --cwd $data_dir &> "$logs_dir/z1" &

o="0"
dgraph alpha -o $o -p "p$o" -w "w$o" --cwd $data_dir --tls_dir "$PWD/tls" &> "$logs_dir/a$o" &

o="1"
dgraph alpha -o $o -p "p$o" -w "w$o" --cwd $data_dir --tls_dir "$PWD/tls" &> "$logs_dir/a$o" &
