#!/bin/bash

test_name=$0

logs_dir=$PWD"/logs/${test_name:2}"

rm -rf $logs_dir; mkdir $logs_dir

# for mac
dgosx down && dgosx up &> "$logs_dir/docker_logs" & 


# for ubuntu
#docker-compose up &> "$logs_dir/docker_logs" &
